name: "Terraform Main Branch Validation"

on:
  push:
    branches: [main]

jobs:
  post-to-slack:
    uses: entur/gha-slack/.github/workflows/post.yml@v3
    secrets: inherit
    with:
      channel_id: "C08R095NTG8"
      message: |
        ✅ *Push to main completed in* 📦 <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>
        👤 *Author:* ${{ github.event.head_commit.author.name }}
  post-failure-to-slack:
    if: failure()
    needs: [terraform]
    uses: entur/gha-slack/.github/workflows/post.yml@v3
    secrets: inherit
    with:
      channel_id: "C05ERL9N22V"
      message: |
        🚨 *Workflow failed in* 📦 <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>
        *Branch:* `${{ github.ref_name }}`
        *Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.event.head_commit.message }}>
        *Author:* ${{ github.event.head_commit.author.name }}
        *Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow run>
  terraform:
    name: "Terraform Validation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.13

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          cd modules/dataform
          terraform init

      - name: Terraform Validate
        run: |
          cd modules/dataform
          terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: |
          cd modules/dataform
          tflint

